# Generated by Django 5.0.1 on 2024-02-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
    ]
