# Generated by Django 5.0.1 on 2024-02-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
