# Generated by Django 5.0.1 on 2024-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('FB', 'Fiction Books'), ('NB', 'Non Fiction Books'), ('MB', 'Mystery Books'), ('EC', 'Education Books')], max_length=2)),
                ('book_image', models.ImageField(upload_to='book')),
            ],
        ),
    ]
