# Generated by Django 5.0.1 on 2024-03-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
    ]
