# Generated by Django 5.0.1 on 2024-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
